DATA:
  NUM_CLASSES: 1000
  TEST: ('imagenet',)
  TRAIN: ('imagenet',)
  PATH: './datasets'
  DATA_DIR: './data'
LOSS:
  LOSS: 'xentropy'
  LABEL_SMOOTHING: 0.1
INPUT:
  INTERPOLATION: 3
AUG:
  MIXUP_PROB: 1.0
  MIXUP: 0.8
  MIXCUT: 1.0
  TIMM_AUG:
    USE_TRANSFORM: True
    RE_COUNT: 1
    RE_MODE: pixel
    RE_SPLIT: False
    RE_PROB: 0.25
    AUTO_AUGMENT: rand-m9-mstd0.5-inc1
    HFLIP: 0.5
    VFLIP: 0.0
    COLOR_JITTER: 0.4
DATALOADER:
  BSZ: 8
  RE: 'no'
  WORKERS: 2
AMP:
  ENABLED: True
OPTIM:
  OPT: 'adamw'
  LR: 5e-4
  MOM: 0.9
  NU: 1.0
  WD: 0.05
  WD0: 0.0
  EPOCHS: 300
  WARMUP: 0
  DROP_FREQ: 30
  DROP_FACTOR: 10.0
  VAL: 0
  TEST_FREQ: 1000
  ADAM:
    BETA1: 0.9
    BETA2: 0.999
MODEL:
  ARCH: msvit
  FREEZE_CONV_BODY_AT: -1
  MODEL_PATH: /home/rzhang/Dev/vision-longformer/pretrained/model_best.pth
  NONLINEARITY: celu
  PRETRAINED: True
  VIT:
    AVG_POOL: False
    DROP: 0.0
    DROP_PATH: 0.1
    MSVIT:
      ARCH: l1,h1,d48,n1,s1,g1,p4,f7_l2,h3,d96,n1,s1,g1,p2,f7_l3,h3,d192,n9,s0,g1,p2,f7_l4,h6,d384,n1,s0,g0,p2,f7
      ATTN_TYPE: longformerhand
      LN_EPS: 1e-06
      ONLY_GLOBAL: False
      SHARE_KV: True
      SHARE_W: True
      SW_EXACT: 0
    NORM_EMBED: True
SOLVER:
  LR_POLICY: 'cosine'
  WARMUP_FACTOR: 0.002
  WARMUP_EPOCHS: 5.0
  MIN_LR: 1e-6
OUTPUT_DIR: "/tmp"
BACKUP_LOG_DIR: ""
LOG_FREQ: 100
EVALUATE: True
ONLY_SAVE_LAST: 0
